name: Lint Commit Messages
on:
  # develop 브랜치에 push 할 때
  push:
    branches:
      - develop

  # master 브랜치로 PR 할 때
  pull_request:
    branches:
      - master

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
