name: Lint Commit
on:
  # feature, hotfix 브랜치에 push 할 때
  push:
    branches:
      - feature/**
      - hotfix/**

  # develop, master/main 브랜치로 PR 할 때
  pull_request:
    branches:
      - develop
      - master
      - main

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v5
